### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by mohsinht** [jsdom/hr-time#10]
I'm getting an error in console and my React App is not rendering because of the issue.
Its working well on Firefox and Chrome. The time format in w3c-hr-time library is causing some issue.

My safari version: 10.1.1

`[Error] ReferenceError: Can't find variable: hrtime testClockAccuracy (clock-is-accurate.js:9) Eval Code (clock-is-accurate.js:46) eval ./node_modules/w3c-hr-time/lib/clock-is-accurate.js (main.bundle.js:17969) __webpack_require__ (main.bundle.js:64) Eval Code (performance.js:5) eval ./node_modules/w3c-hr-time/lib/performance.js (main.bundle.js:17993) __webpack_require__ (main.bundle.js:64) Eval Code (index.js:4) eval ./node_modules/w3c-hr-time/index.js (main.bundle.js:17945) __webpack_require__ (main.bundle.js:64) (anonymous function) (Window.js:5) Eval Code (Window.js:703) eval ./node_modules/jsdom/lib/jsdom/browser/Window.js (main.bundle.js:4994) __webpack_require__ (main.bundle.js:64) (anonymous function) (api.js:13) Eval Code (api.js:340) eval ./node_modules/jsdom/lib/api.js (main.bundle.js:4982) __webpack_require__ (main.bundle.js:64) (anonymous function) (index.js:1) Eval Code (index.js:1:130) eval ./node_modules/react-sketch/dist/index.js (main.bundle.js:14955) __webpack_require__ (main.bundle.js:64) Eval Code (Test_Whiteboard.jsx:7:90) eval ./_devapp/Test_Whiteboard.jsx (main.bundle.js:308) __webpack_require__ (main.bundle.js:64) Eval Code (app.js:19:95) eval ./_devapp/app.js (main.bundle.js:380) __webpack_require__ (main.bundle.js:64) Eval Code (app.scss:1) eval (anonymous function) (main.bundle.js:18394) __webpack_require__ (main.bundle.js:64) (anonymous function) (main.bundle.js:199) Global Code (main.bundle.js:200)`

**Comment by TimothyGu** [comment]
Unfortunately, we can't debug this. Your setup makes use of many other packages like webpack and React so it's difficult to pin down whether there is a problem with our code or your setup.
