### ISSUE TITLE
Meltdown/Spectre & aligning with browsers

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/hr-time#2]
One of the mitigations for the recent Meltdown/Spectre attacks is reducing the resolution of high performance timers. I don't think we have anything to worry regarding attacks but aligning with the spec/what's implemented by browsers is indeed a goal of this project.

So far, browsers are [doing different things](https://github.com/w3c/hr-time/pull/55#issuecomment-355665485) regarding this, but all of them cap the resolution to at least 20 microseconds, with some of them also adding jitters using a cryptographically secure source (see [Blink's implementation](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/TimeClamper.cpp), which caps resolution to 100 microseconds). See also w3c/hr-time#55, which is an initial attempt at documenting the actual resolution in the spec.

What should we do?

**Comment by Zirro** [comment]
Thanks for staying on top of this. With both Blink and Webkit capping the resolution at 100 microseconds, I think we should follow them until it is addressed in the spec.

Based on that pull request it seems like the addition of jitter may become part of the specification as well, so if depending on Node's crypto module isn't problematic for browserify etc (I would assume it's used by at least one of jsdom's dependencies already) it would be good to add.
