### ISSUE TITLE
Publish latests changes without infinite loop

### ISSUE THREAD

**Issue by jquintozamora** [jsdom/hr-time#9]
There is an issue with infinite loop in that line: https://github.com/jsdom/w3c-hr-time/blob/v1.0.1/lib/calculate-clock-offset.js#L17

**Comment by falkenhawk** [comment]
Hi, could a fixed version be published already? I've just lost a whole day debugging why my tests were getting stuck in an infinite loop

**Comment by falkenhawk** [comment]
@TimothyGu thank you!
